# Optimized Nixpacks configuration for Restyle.ai Railway deployment

[variables]
PYTHON_VERSION = "3.11"
PIP_NO_CACHE_DIR = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"

[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "gcc",
  "glibc",
  "mesa",
  "xorg.libSM",
  "xorg.libXext",
  "xorg.libXrender",
  "libjpeg_turbo",
  "libpng",
  "freetype",
  "fontconfig",
  "pkg-config"
]

[phases.install]
cmds = [
  "pip install --upgrade pip setuptools wheel",
  "pip install --no-cache-dir torch torchvision --index-url https://download.pytorch.org/whl/cpu",
  "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput --clear",
  "chmod +x fast_start.sh"
]

[phases.start]
cmd = "bash fast_start.sh"
