
providers = []

[variables]
PIP_NO_CACHE_DIR = "1"

[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "python311Packages.virtualenv",
  "gcc",
  "zlib",
  "zlib.dev",
  "postgresql",
  "openssl",
  "mesa",
  "xorg.libSM",
  "xorg.libXext", 
  "xorg.libXrender",
  "libjpeg_turbo",
  "libpng",
  "freetype",
  "fontconfig"
]

[phases.install]
cmds = [
  "echo 'Python binary:' $(which python)",
  "python --version",
  "ldd --version || true",
  "python -m venv venv",
  "source venv/bin/activate && pip install --upgrade pip",
  "source venv/bin/activate && pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu",
  "source venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "source venv/bin/activate && python manage.py collectstatic --noinput --clear",
  "chmod +x fast_start.sh"
]

[phases.start]
cmd = "export LD_LIBRARY_PATH=$(find /nix/store -type d -name lib | tr '\n' ':'); echo 'Python binary at runtime:' $(which python); python --version; ldd --version || true; source venv/bin/activate && bash fast_start.sh"