# Generated by Django 4.2.13 on 2025-07-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ebay_category_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
