name: EAS Update

on:
  push:
    branches:
      - main

jobs:
  eas-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install -g eas-cli
      - run: npm ci
        working-directory: ./restyle-mobile
      - run: eas update --branch production --non-interactive --message "Automated update from CI/CD"
        working-directory: ./restyle-mobile
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }} 
